import type { Metadata } from "next";
import dynamic from 'next/dynamic';
import { ThemeProvider } from '@/app/ProviderTheme';
//import { Lavishly_Yours } from 'next/font/google';
//import localFont from "next/font/local";

import Image from "next/image";
import imgAlphaLogo from "/public/alpha_letter.png";
import "./globals.css";
//import Header from "./components/Header";
import Footer from "./components/Footer";

/* const lavishlyFont = Lavishly_Yours({
  subsets: ["latin"],
  weight: "400",
}); */

/* const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
}); */

export const metadata: Metadata = {
  title: {
    default: "alpha",
    template: "%s | Fabio"
  },
  description: 'Generated by NextJS14',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const DynamicHeader = dynamic(() => import('@/app/components/Header'), {
    loading: () => <p>Loading...</p>,
  });
  //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-background absolute -z-20 w-full min-h-screen bg-slate-50 dark:text-slate-50 dark:bg-slate-900">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <DynamicHeader />
            <div className="fixed -z-10 flex flex-col items-center justify-center w-full h-full">
              <Image 
                src={imgAlphaLogo} 
                width={626} height={626} 
                alt="no img alpha" 
                className="w-[700px] h-[700px] dark:filter dark:invert opacity-50 dark:opacity-15"
              />
            </div>
            {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
